name: New Caller Workflow

on:
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      name: 'Ashiq'
      greeting: 'Hellooooooooooo'
